#!groovy
podTemplate(
  label: "skopeo-pod",
  cloud: "openshift",
  inheritFrom: "maven",
  containers: [
    containerTemplate(
      name: "jnlp",
      image: "docker-registry.default.svc:5000/e80d-jenkins/jenkins-agent-appdev",
      resourceRequestMemory: "1Gi",
      resourceLimitMemory: "2Gi",
      resourceRequestCpu: "1",
      resourceLimitCpu: "2"
    )
  ]
) {
  node('skopeo-pod') {
    // Define Maven Command to point to the correct
    // settings for our Nexus installation
    def mvnCmd = "mvn -s ../nexus_settings.xml"

    // Checkout Source Code.
    stage('Checkout Source') {
      checkout scm
    }

    // Build the Tasks Service
    dir('openshift-tasks') {
      // The following variables need to be defined at the top level
      // and not inside the scope of a stage - otherwise they would not
      // be accessible from other stages.
      // Extract version from the pom.xml
      def version = getVersionFromPom("pom.xml")

      // TBD Set the tag for the development image: version + build number
      def devTag  = "${version}-${BUILD_NUMBER}"
      // Set the tag for the production image: version
      def prodTag = "${version}"

      // Using Maven build the war file
      // Do not run tests in this step
      stage('Build war') {
        echo "Building version ${devTag}"

        sh "${mvnCmd} clean package -DskipTests"
      }

      // TBD: The next two stages should run in parallel
      stage("Tests and Analysis") {
        // Using Maven run the unit tests
      	  parallel 'A': {
		    	stage('Unit Tests') {
				echo "Running Unit Tests"
			  	sh "${mvnCmd} test"
		    	}
		    },
        // Using Maven to call SonarQube for Code Analysis
		   'B': {			
		 	stage('Code Analysis') {
			    echo "Running Code Analysis"
			    sh "${mvnCmd} sonar:sonar -Dsonar.host.url=http://sonarqube.gpte-hw-cicd.svc.cluster.local:9000 -Dsonar.projectName=${JOB_BASE_NAME}-${devTag} -Dsonar.projectVersion=${devTag}"
		    	}
		   }
      }

      // Publish the built war file to Nexus
      stage('Publish to Nexus') {
        echo "Publish to Nexus"

        sh "${mvnCmd} deploy -DskipTests=true -DaltDeploymentRepository=nexus::default::http://nexus3.gpte-hw-cicd.svc.cluster.local:8081/repository/releases/"
      }

      // Build the OpenShift Image in OpenShift and tag it.
      stage('Build and Tag OpenShift Image') {
        echo "Building OpenShift container image tasks:${devTag}"

        sh "oc start-build tasks --follow --from-file=http://nexus3.gpte-hw-cicd.svc.cluster.local:8081/repository/releases/org/jboss/quickstarts/eap/tasks/${version}/tasks-${version}.war -n e80d-tasks-dev"
        openshiftTag alias: 'false', destStream: 'tasks', destTag: devTag, destinationNamespace: 'e80d-tasks-dev', namespace: 'e80d-tasks-dev', srcStream: 'tasks', srcTag: 'latest', verbose: 'false'
      }

      // Deploy the built image to the Development Environment.
      stage('Deploy to Dev') {
        echo "Deploying container image to Development Project"

	sh "oc set env  dc/tasks VERSION='${devTag} (tasks-dev)' -n e80d-tasks-dev"
        sh "oc set image dc/tasks tasks=docker-registry.default.svc:5000/e80d-tasks-dev/tasks:${devTag} -n e80d-tasks-dev"

        openshiftDeploy depCfg: 'tasks', namespace: 'e80d-tasks-dev', verbose: 'false', waitTime: '', waitUnit: 'sec'
        openshiftVerifyDeployment depCfg: 'tasks', namespace: 'e80d-tasks-dev', replicaCount: '1', verbose: 'false', verifyReplicaCount: 'false', waitTime: '', waitUnit: 'sec'
        openshiftVerifyService namespace: 'e80d-tasks-dev', svcName: 'tasks', verbose: 'false'

	sh "curl -s -i -H 'Content-Length: 0' -X POST http://tasks-e80d-tasks-dev.apps.na311.openshift.opentlc.com/ws/tasks/integration_test_1"
      }

      // Copy Image to Nexus container registry
      stage('Copy Image to Nexus container registry') {
        echo "Copy image to Nexus container registry"

        sh "skopeo copy --src-tls-verify=false --dest-tls-verify=false --src-creds openshift:\$(oc whoami -t) --dest-creds admin:redhat \
	docker://docker-registry.default.svc:5000/e80d-tasks-dev/tasks:${devTag} \
	docker://nexus-registry.gpte-hw-cicd.svc.cluster.local:5000/tasks:${devTag}"

	openshiftTag alias: 'false', destStream: 'tasks', destTag: prodTag, destinationNamespace: 'e80d-tasks-dev', namespace: 'e80d-tasks-dev', srcStream: 'tasks', srcTag: devTag, verbose: 'false'
      }

      // Blue/Green Deployment into Production
      // -------------------------------------
      def destApp   = "tasks-green"
      def activeApp = ""

      stage('Blue/Green Production Deployment') {
        activeApp = sh(returnStdout: true, script: "oc get route tasks -n e80d-tasks-prod -o jsonpath='{ .spec.to.name }'").trim()
        if (activeApp == "tasks-green") {
          destApp = "tasks-blue"
        }
        echo "Active Application:      " + activeApp
        echo "Destination Application: " + destApp

        sh "oc set env dc/tasks-blue VERSION='${prodTag} (tasks-blue)' -n e80d-tasks-prod"
        sh "oc set env dc/tasks-green VERSION='${prodTag} (tasks-green)' -n e80d-tasks-prod"
        sh "oc set image dc/${destApp} ${destApp}=docker-registry.default.svc:5000/e80d-tasks-dev/tasks:${prodTag} -n e80d-tasks-prod"

        openshiftDeploy depCfg: destApp, namespace: 'e80d-tasks-prod', verbose: 'false', waitTime: '', waitUnit: 'sec'
        openshiftVerifyDeployment depCfg: destApp, namespace: 'e80d-tasks-prod', replicaCount: '1', verbose: 'false', verifyReplicaCount: 'true', waitTime: '', waitUnit: 'sec'
        openshiftVerifyService namespace: 'e80d-tasks-prod', svcName: destApp, verbose: 'false'

        sh "curl -s -i -H 'Content-Length: 0' -X POST http://tasks-e80d-tasks-prod.apps.na311.openshift.opentlc.com/ws/tasks/integration_test_1"

      }

      stage('Switch over to new Version') {
        echo "Switching Production application to ${destApp}."
        sh 'oc patch route tasks -n e80d-tasks-prod -p \'{"spec":{"to":{"name":"' + destApp + '"}}}\''
      }
    }
  }
}

// Convenience Functions to read version from the pom.xml
// Do not change anything below this line.
// --------------------------------------------------------
def getVersionFromPom(pom) {
  def matcher = readFile(pom) =~ '<version>(.+)</version>'
  matcher ? matcher[0][1] : null
}
